server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: questions-service
          uri: http://localhost:8082
          predicates:
            - Path=/questions/**
          
        - id: quiz-service
          uri: http://localhost:8083
          predicates:
            - Path=/quiz/**

        - id: student-service
          uri: http://localhost:8084
          predicates:
            - Path=/students/**

        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
